version: '3.8'

services:
  server:
    build:
      context: wb_0_service/
      args:
        DB_PORT: 5432
        DB_HOST: db
        DB_NAME: order_database
        DB_USER: orders_user
        DB_PASSWORD: 123Qweqwe.
        LOG_LEVEL: trace
        ENVIRONMENT: prod
        NATS_URL: nats://host.docker.internal:4222
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - 5000:5432
    volumes:
      - wb_0:/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  wb_0: